### PR TITLE
Use console.debug when available

### LINKED ISSUE #12: log.debug uses console.log
* Node Version: 10.13.0
* NPM Version: 6.10.3
* loglevelnext Version: 3.0.1

### Expected Behavior

`log.debug` uses `console.debug`.

### Actual Behavior

`log.debug` uses `console.log`

### How can we reproduce the behavior?

Use `log.debug` but disable debug in the browser console. The messages will remain.

---

The debug method is hardcoded to do this:

https://github.com/shellscape/loglevelnext/blob/cc35e2878fc82a1c3dcde7ef6ac16e2e15164873/lib/factory/MethodFactory.js#L95-L98

Could this be made optional or removed completely? I configure loglevel to be silent in production, but it's nice in development to be able to use the browser's log level toggles to enable/disable debug messages.

### PR DESCRIPTION
**Pull request by RazerM**
Fixes #12 

Please check one:
- [ ] New tests created for this change
- [x] Tests updated for this change

This PR:
- [ ] Adds new API
- [x] Extends existing API, backwards-compatible
- [ ] Introduces a breaking change
- [ ] Fixes a bug

---

I think the existing fallback to console.log will work. Let's see if node 6 tests pass in CI.

### CODE REVIEW

**Comment by RazerM** [comment]
@shellscape can you get CI working. I guess you don't have it running on a schedule so it's hard to contribute.

**Comment by shellscape** [comment]
CI is fixed. Once the conflicts are cleaned up you should be good.

**Comment by RazerM** [comment]
@shellscape I don't know why Travis CI didn't respond but this should be good to merge

**Comment by shellscape** [comment]
I'll check it out

**Comment by shellscape** [comment]
@RazerM sorry this took a while to get merged. Slipped under the radar for a bit.

**Pull request merged**
